### ISSUE TITLE
module (png core chunk tEXt) does not exist

### ISSUE THREAD

**Issue by aconchillo** [artyom-poptsov/guile-png#2]
Hi! I'm getting an error in `chund-decoder.scm` because the module `(png core chunk tEXt)` does not exist, however `(png core chunk tEXT)` does. I'm not familiar with PNG, not sure if there's any difference.

```
Backtrace:
In ice-9/boot-9.scm:
   2836:4 19 (save-module-excursion _)
  3564:26 18 (_)
In unknown file:
          17 (primitive-load-path "png/chunk-decoder" #<procedure 10…>)
In ice-9/eval.scm:
   721:20 16 (primitive-eval _)
In ice-9/psyntax.scm:
  1229:36 15 (expand-top-sequence _ _ _ #f _ _ _)
  1221:19 14 (parse _ (("placeholder" placeholder)) ((top) #(# # …)) …)
   259:10 13 (parse _ (("placeholder" placeholder)) (()) _ c&e (eval) …)
In ice-9/eval.scm:
   293:34 12 (_ #<module (#{ g153}#) 1067adaa0>)
In ice-9/boot-9.scm:
   3411:4 11 (define-module* _ #:filename _ #:pure _ #:version _ # _ …)
  3424:24 10 (_)
   222:29  9 (map1 _)
   222:29  8 (map1 _)
   222:29  7 (map1 _)
   222:29  6 (map1 _)
   222:29  5 (map1 _)
   222:29  4 (map1 (((png core chunk cHRM)) ((png core chunk #)) # …))
   222:29  3 (map1 (((png core chunk tEXt)) ((png core chunk #)) # …))
   222:17  2 (map1 (((png core chunk tEXT)) ((png core chunk #)) # …))
   3330:6  1 (resolve-interface (png core chunk tEXT) #:select _ # _ …)
  1685:16  0 (raise-exception _ #:continuable? _)

ice-9/boot-9.scm:1685:16: In procedure raise-exception:
no code for module (png core chunk tEXT)
```

**Comment by artyom-poptsov** [comment]
Hello,

could you elaborate on how did you get this error?

Thanks!

**Comment by aconchillo** [comment]
> Hello,
> 
> could you elaborate on how did you get this error?
> 
> Thanks!

Hi, sorry for not providing more info. The steps are mainly:

```
autoreconf -vif
./configure
make
```

This happens on both upstream and from the tarball.

**Comment by artyom-poptsov** [comment]
Hello,

unfortunately I could not reproduce the error.  I tried to build from `master` both Guile-SMC and Guile-PNG and ran tests, but no error occurred.

Maybe you could tell more about the environment where you run the build?

Thanks!

**Comment by aconchillo** [comment]
Hi! I think I know what the problem is. On macOS, file names are case insensitive, so `tEXT` and `tEXt` are the same. 🤦

**Comment by artyom-poptsov** [comment]
Hello Aleix!

Oh, that's an unfortunate situation indeed.  Are there any workarounds on macOS for that, or this should be fixed in the library itself?

I wonder what is the correct way to handle that.  Maybe I should merge those two modules together, but this will break the overall structure of modules...

**Comment by aconchillo** [comment]
> Hello Aleix!
> 
> Oh, that's an unfortunate situation indeed. Are there any workarounds on macOS for that, or this should be fixed in the library itself?
> 

Unfortunately I think it needs to be done in the library. There's a setting on macOS where you can tell the file system to be case-sensitive but of course we can't ask for the users to do that.

> I wonder what is the correct way to handle that. Maybe I should merge those two modules together, but this will break the overall structure of modules...

I'm not familiar with how guile-png works :-(.

**Comment by artyom-poptsov** [comment]
Hello!  The issue now should be fixed in ed8f11646989e832a7470f715f1b63e33124b6ca

Please check Guile-PNG from the `master` branch.

**Comment by aconchillo** [comment]
Hi! This is working now. Thank you! Closing.

**Comment by aconchillo** [comment]
Also, I believe it now looks better with all lowercase. 🙌
